/*
 * generated by Xtext 2.12.0
 */
package com.metagamedsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MetaGameLanguageStandaloneSetup extends MetaGameLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new MetaGameLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
