/*
 * generated by Xtext 2.12.0
 */
package com.metagamedsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import com.metagamedsl.metaGameLanguage.Game

@RunWith(XtextRunner)
@InjectWith(MetaGameLanguageInjectorProvider)
class MetaGameLanguageParsingTest {
	@Inject
	ParseHelper<Game> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
